---
- name: create dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    recurse: true
  loop:
    - "{{ path }}"

- name: transfer files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: '{{ item.dest }}'
    mode: '{{ item.mode }}'
  loop: 
    - { src: env.j2, dest: '{{ path }}/.env', mode: '644' }
    - { src: docker-compose.yml.j2, dest: '{{ path }}/docker-compose.yml', mode: '644' }

- name: run docker-compose up
  ansible.builtin.shell: docker-compose up --build -d
  args:
    chdir: '{{ path }}'
  ignore_errors: true
