---
- name: include docker install play
  ansible.builtin.import_playbook: docker-install.yml
  
- name: rocketchat docker install
  become: true
  hosts: '{{ host }}'
  vars:
    fqdn: example.com
    server_name: "rocket.{{ fqdn }}"
    rocket_root_url: "https://rocket.{{ fqdn }}"

  roles:
  - roles/rocketchat-docker-install
